In [7]:
import numpy as np
y=np.array([1,2,3,4])
print(y)
print(y.ndim)
ya=np.array([[1,2,3,4],[3,4,5,6]])
print(ya)
print(ya.ndim)

[1 2 3 4]
1
[[1 2 3 4]
 [3 4 5 6]]
2


list k array banailam

2 dimention er khetre protita 1d array er size same hobe

In [4]:
a=[]
for i in range(1,5):
    int_a=int(input("enter: "))
    a.append(int_a)
print(np.array(a))

12
12
45
3
[12 12 45  3]


In [10]:
z1=np.zeros(4)
z2=np.zeros((4,3))
print(z1)
print(z2)


[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# ones

In [11]:
z1=np.ones(4)
z2=np.ones((4,3))
print(z1)
print(z2)


[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# empty

In [12]:
z1=np.empty(4)

print(z1)



[1. 1. 1. 1.]


In [13]:
z1=np.arange(4)

print(z1)

[0 1 2 3]


# Diagonal

In [14]:
z1=np.eye(4)

print(z1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
z1=np.eye(4,3)

print(z1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# linspace

In [18]:
z1=np.linspace(0,20,num=5)

print(z1)

[ 0.  5. 10. 15. 20.]


# Random
rand()

just positve value dei

In [20]:
z1=np.random.rand(5)

print(z1)
z2=np.random.rand(2,5)

print(z2)

[0.68702684 0.71806313 0.37284612 0.1677721  0.24462977]
[[0.30673807 0.56304341 0.67619754 0.84496386 0.23876741]
 [0.9529687  0.20413895 0.82459464 0.99978414 0.04595354]]


# randn 
negitavie + duitai dei

# ranf()
0 k include korbe but 1 k na r value 1 er kasakasi hobe

In [21]:
z1=np.random.ranf(5)

print(z1)

[0.38111464 0.478576   0.16693288 0.29433941 0.83121507]


# randint
(min,max,total number)

In [22]:
z1=np.random.randint(5,20,5)

print(z1)

[13 15 16  9  5]


Datatype

In [1]:
import numpy as np
var=np.array(["a","b"])
print("datatype: ",var.dtype)

datatype:  <U1


In [2]:
import numpy as np
var=np.array([1.1,2.2])
print("datatype: ",var.dtype)

datatype:  float64


In [4]:
var=np.array([1.1,2.2],dtype=np.int8)
print("datatype: ",var.dtype)
print(var)

datatype:  int8
[1 2]


In [6]:
var=np.array([1,2],dtype="f")
print("datatype: ",var.dtype)
print(var)

datatype:  float32
[1. 2.]


In [8]:
var=np.array([1,2])
var2=np.float32(var)
print("datatype: ",var.dtype)
print("datatype: ",var2.dtype)
print(var)
print(var2)

datatype:  int32
datatype:  float32
[1 2]
[1. 2.]


In [9]:
var=np.array([1,2])
var2=var.astype(float)
print("datatype: ",var.dtype)
print("datatype: ",var2.dtype)
print(var)
print(var2)

datatype:  int32
datatype:  float64
[1 2]
[1. 2.]


# Arithematic operation


In [10]:
import numpy as np
var=np.array([1,2,3,4])
v1=var/3
print(v1)

[0.33333333 0.66666667 1.         1.33333333]


+,-,* ,% same vabe hobe

In [11]:
var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
v33=var+var2
print(v33)

[2 4 6 8]


same kaj np.add(a,b)//var,3/var,var2
np.subtract,sqrt,multiply,divide,mod,power.reciprocal(a)


In [13]:
var=np.array([1,2,3,4])
v1=np.reciprocal(var)
print(v1)

[1 0 0 0]


## 2d array

In [12]:
var=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[1,2,3,4]])
v33=var+var2
print(v33)

[[2 4 6 8]
 [2 4 6 8]]


In [16]:
var=np.array([7,6,3,4])
print("min: ",np.min(var),np.argmin(var))

min:  3 2


axis=0 column borabor min value

axis=1 row borabor min value

In [19]:
var=np.array([[1,2,3,4],[14,6,2,7]])
print(np.min(var,axis=0))

[1 2 2 4]


In [21]:
var=np.array([[1,2,3,4],[14,6,2,7]])
print(np.min(var,axis=1))

[1 2]


In [23]:
var=np.array([1,2,3,4])
v1=np.sin(var)
print(v1)
print(np.cumsum(var))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1  3  6 10]


# shape

In [26]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var.shape)

(2, 4)


In [28]:
var=np.array([1,2,3,4],ndmin=4)
print(var.shape)
print(var)

(1, 1, 1, 4)
[[[[1 2 3 4]]]]


3 row 4 column

In [31]:
##reshape
var=np.array([1,2,3,4,5,6,7,8,9])
xa=var.reshape(3,3)
print(xa)
print()
one=xa.reshape(-1)
print(one)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


In [34]:
var=np.array([1,2,3,4])
var1=np.array([1,2,3])
##print(var+var1) dile broadcasting error dibe bcz dim same na
var2=np.array([[1],[2],[3]])
print(var+var2)
##(1,3) (3,1) // 3,3 and 1,1 milse tai addition hose .diff hoile hoito na addition
##(2,1) (2,3) // addition er por (2,3) matrix hobe .max nei

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


# indexing

In [35]:
var=np.array([1,2,3,4])
print(var[-1])

4


In [36]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var[0,2])

3


In [37]:
var=np.array([[[1,2,3,4],[1,2,3,4]]])
print(var[0,1,3])

4


In [39]:
#slicing
var=np.array([1,2,3,4,5,6,7,8,9])
print("2 to 5: ",var[1:5])
print("2 to end: ",var[1:])
print("start to 5: ",var[:5])
#starti,endi,step
print("stop: ",var[::2])
print("stop: ",var[1:5:2])

2 to 5:  [2 3 4 5]
2 to end:  [2 3 4 5 6 7 8 9]
start to 5:  [1 2 3 4 5]
stop:  [1 3 5 7 9]
stop:  [2 4]


In [40]:
var=np.array([[1,2,3,4],[1,2,7,6],[3,5,6,7]])
print("2 to 6: ",var[1,1:])

2 to 6:  [2 7 6]


# iteration


In [43]:
var=np.array([[[1,2,3,4],[1,2,3,4]]])
for i in var:
    for j in i:
        for k in j:
            print(k)
print()          
#same kaj kora jai nditer diye
for i in np.nditer(var):
    print(i)

1
2
3
4
1
2
3
4

1
2
3
4
1
2
3
4


In [45]:
var=np.array([[[1,2,3,4],[1,2,3,4]]])
#index+data
for i,d in np.ndenumerate(var):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


# copy vs view

In [49]:
var=np.array([1,2,3,4,5,6,7,8,9])

c=var.copy()
var[1]=40
v=var.view()
print(var)
print(c)
print(v)
# view change hoi ,copy hoi na

[ 1 40  3  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]
[ 1 40  3  4  5  6  7  8  9]


# join array

In [54]:
var=np.array([1,2,3,4])
var2=np.array([5,6,7,8,9])
new=np.concatenate((var,var2))
print(new)

[1 2 3 4 5 6 7 8 9]


In [58]:
var=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[1,2,3,4]])
new=np.concatenate((var,var2),axis=0)
new1=np.concatenate((var,var2),axis=1)
print(new)
print()
print(new1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]]


In [4]:
import numpy as np
var=np.array([1,2,3,4])
var2=np.array([5,6,7,8])
new=np.stack((var,var2),axis=1) 
new1=np.hstack((var,var2)) #row
new2=np.vstack((var,var2)) #column
new3=np.dstack((var,var2)) #height
print(new)
print()
print(new1)
print()
print(new2)
print()
print(new3)
print()

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]



#    split array

In [7]:
var=np.array([1,2,3,4,5,6,7,8,9])

c=np.array_split(var,3)
print(c)
print(c[0])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]


In [10]:
var=np.array([[1,2,3],[4,5,6],[7,8,9]])

c=np.array_split(var,3)
c1=np.array_split(var,3,axis=1)
print(c)
print(c1)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


# search

In [13]:
var=np.array([1,2,3,4,5,2,7,8,2])

c=np.where(var==2)
print(c)
c1=np.where((var%2)==0)
print(c1)

(array([1, 5, 8], dtype=int64),)
(array([1, 3, 5, 7, 8], dtype=int64),)


In [18]:
var=np.array([1,2,3,4,6,7,8,9,10])#sorted array lagbe

c=np.searchsorted(var,[5,6,7],side="left")
print(c)

[4 4 5]


# sort

In [20]:
var=np.array([1,2,5,8,3,0,9])
print(np.sort(var))

[0 1 2 3 5 8 9]


In [21]:
var=np.array([[1,8,5],[4,7,6],[7,8,4]])
print(np.sort(var))

[[1 5 8]
 [4 6 7]
 [4 7 8]]


In [22]:
#filter array
var=np.array(["a","s","d","r"])
f=[True,False,True,True]
n=var[f]
print(n)

['a' 'd' 'r']


In [23]:
#suffle
var=np.array([1,2,5,8,3,0,9])
np.random.shuffle(var)
print(var)

[1 5 2 3 0 9 8]


In [27]:
var=np.array([1,2,5,8,3,0,9,0,4,5,2,1])
cx=np.unique(var,return_index=True,return_counts=True)
print(cx)

(array([0, 1, 2, 3, 4, 5, 8, 9]), array([5, 0, 1, 4, 8, 2, 3, 6], dtype=int64), array([2, 2, 2, 1, 1, 2, 1, 1], dtype=int64))


In [37]:
#resize
var=np.array([1,2,5,8,3,0,9])
x=np.resize(var,(3,2))
print(x)
print()
print(x.flatten(order="F"))#c f k a order daoa jai .bby default c thake
print("ravel: ",np.ravel(x,order="K"))#same

[[1 2]
 [5 8]
 [3 0]]

[1 5 3 2 8 0]
ravel:  [1 2 5 8 3 0]


# Insert

In [39]:
var=np.array([1,2,5,8,3,0,9])
x=np.insert(var,2,40)
x1=np.insert(var,(2,4),4.9)
print(x)
print(x1)

[ 1  2 40  5  8  3  0  9]
[1 2 4 5 8 4 3 0 9]


In [44]:
var=np.array([[1,8,5],[4,7,6],[7,8,4]])
v1=np.insert(var,2,6,axis=1)
print(v1)
v2=np.insert(var,2,[22,23,24],axis=1)#3 value e dite hobe
print(v2)

[[1 8 6 5]
 [4 7 6 6]
 [7 8 6 4]]
[[ 1  8 22  5]
 [ 4  7 23  6]
 [ 7  8 24  4]]


In [45]:
var=np.array([1,2,5,8,3,0,9])
x=np.append(var,6.5)
print(x)

[1.  2.  5.  8.  3.  0.  9.  6.5]


In [49]:
var=np.array([[1,8,5],[4,7,6],[7,8,4]])
v1=np.append(var,[[45,46,67]],axis=0)
print(v1)

[[ 1  8  5]
 [ 4  7  6]
 [ 7  8  4]
 [45 46 67]]


In [50]:
#Delete
var=np.array([1,2,5,8,3,0,9])
x=np.delete (var,2)
print(x)

[1 2 8 3 0 9]
